### ISSUE TITLE
Less transformation of variables starting with tilde

### ISSUE THREAD

**Issue by aminpaks** [aminpaks/typescript-library-bundler#10]
We should consider supporting the tilde `~` for variables as well.

Use case:
```less
@import '~a-node-module/less/variables.less'; // This is supported

@path: '~a-node-module/less/variables.less'; // This should become as well

.a-class {
  background-url: data-url('some/extension', @{path});
}
```
